# Generated by Django 5.1.1 on 2024-10-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='tag',
            field=models.ManyToManyField(to='produit.tag'),
        ),
    ]
