# Generated by Django 4.2.16 on 2024-10-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_produit_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('alimentaire', 'Alimentaire'), ('electronique', 'Electronique'), ('vetement', 'Vetement'), ('mobilier', 'Mobilier'), ('divers', 'Divers')], default='alimentaire', max_length=200),
        ),
    ]
