# Generated by Django 5.1.1 on 2024-10-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
