# Generated by Django 4.2.16 on 2024-10-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_produit_categorie'),
        ('commande', '0003_commande_quantite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ManyToManyField(to='produit.produit'),
        ),
    ]
