# Generated by Django 4.2.16 on 2024-10-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0004_remove_commande_produit_commande_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant_total',
            field=models.FloatField(null=True),
        ),
    ]
