# Generated by Django 4.2.16 on 2024-10-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0005_commande_montant_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='montant_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
