# Generated by Django 4.2.16 on 2024-10-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0006_alter_commande_montant_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='montant_total',
        ),
    ]
